<?php

namespace Proxies\__CG__\IIT\IhmBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Resultat extends \IIT\IhmBundle\Entity\Resultat implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'id', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'buteq1', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'buteq2', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'pointeq1', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'pointeq2', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'idpartie', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'idequipe1', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'idequipe2', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'logo1', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'logo2');
        }

        return array('__isInitialized__', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'id', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'buteq1', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'buteq2', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'pointeq1', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'pointeq2', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'idpartie', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'idequipe1', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'idequipe2', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'logo1', '' . "\0" . 'IIT\\IhmBundle\\Entity\\Resultat' . "\0" . 'logo2');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Resultat $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setButeq1($buteq1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setButeq1', array($buteq1));

        return parent::setButeq1($buteq1);
    }

    /**
     * {@inheritDoc}
     */
    public function getButeq1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getButeq1', array());

        return parent::getButeq1();
    }

    /**
     * {@inheritDoc}
     */
    public function setButeq2($buteq2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setButeq2', array($buteq2));

        return parent::setButeq2($buteq2);
    }

    /**
     * {@inheritDoc}
     */
    public function getButeq2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getButeq2', array());

        return parent::getButeq2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointeq1($pointeq1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointeq1', array($pointeq1));

        return parent::setPointeq1($pointeq1);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointeq1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointeq1', array());

        return parent::getPointeq1();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointeq2($pointeq2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointeq2', array($pointeq2));

        return parent::setPointeq2($pointeq2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointeq2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointeq2', array());

        return parent::getPointeq2();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdequipe2(\IIT\IhmBundle\Entity\Equipe $idequipe2 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdequipe2', array($idequipe2));

        return parent::setIdequipe2($idequipe2);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdequipe2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdequipe2', array());

        return parent::getIdequipe2();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdequipe1(\IIT\IhmBundle\Entity\Equipe $idequipe1 = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdequipe1', array($idequipe1));

        return parent::setIdequipe1($idequipe1);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdequipe1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdequipe1', array());

        return parent::getIdequipe1();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpartie(\IIT\IhmBundle\Entity\Partie $idpartie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpartie', array($idpartie));

        return parent::setIdpartie($idpartie);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpartie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpartie', array());

        return parent::getIdpartie();
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo1', array());

        return parent::getLogo1();
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo2', array());

        return parent::getLogo2();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo1($logo1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo1', array($logo1));

        return parent::setLogo1($logo1);
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo2($logo2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo2', array($logo2));

        return parent::setLogo2($logo2);
    }

}
